# Utiliser une image légère Python
FROM python:3.8-slim

# Créer un répertoire pour stocker le modèle
WORKDIR /model

# Copier le fichier du modèle dans le conteneur
COPY traffic_sign_model.h5 /model/traffic_sign_model.h5

# Pas de commande à exécuter
# L'image est juste un conteneur de fichier
